server:
  port: 6443
  error:
    include-stacktrace: never

custom:
  baseUrl: https://localhost:8080
  verifyUser: /v1/user
  anonymusUser: /v1/user/anonymus
  token:
    fields: email, password
    secret: secret
    refreshIntervel: 60
    acessIntervel: 10
